# This file was generated by GoReleaser. DO NOT EDIT.
cask "apogee-desktop" do
  app "Apogee.app"

  version "0.1.10"

  on_macos do
    url "https://github.com/BIwashi/apogee/releases/download/v#{version}/apogee-desktop_#{version}_darwin_universal.zip"
    sha256 "ec52a4333622a5ec3af34bf776bf33d136adab999b2cdce3bff3802c3b662fe2"
  end

  name "apogee-desktop"
  desc "Native macOS window for the apogee multi-agent observability dashboard."
  homepage "https://github.com/BIwashi/apogee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apogee-desktop"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Apogee.app"]
  end

  zap trash: [
      "~/Library/Application Support/apogee-desktop",
      "~/Library/Caches/dev.apogee.desktop",
      "~/Library/Preferences/dev.apogee.desktop.plist",
    ]

end
