# This file was generated by GoReleaser. DO NOT EDIT.
cask "apogee-desktop" do
  app "Apogee.app"

  version "0.1.16"

  on_macos do
    url "https://github.com/BIwashi/apogee/releases/download/v#{version}/apogee-desktop_#{version}_darwin_universal.zip"
    sha256 "aa851d1442035a5703faa023679976eef0c71aedbfc5790f83418d4ade903fbf"
  end

  name "apogee-desktop"
  desc "Native macOS window for the apogee multi-agent observability dashboard."
  homepage "https://github.com/BIwashi/apogee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apogee-desktop"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Apogee.app"]
  end

  zap trash: [
      "~/Library/Application Support/apogee-desktop",
      "~/Library/Caches/dev.apogee.desktop",
      "~/Library/Preferences/dev.apogee.desktop.plist",
    ]

end
