# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apogee < Formula
  desc "Multi-agent observability dashboard for Claude Code."
  homepage "https://github.com/BIwashi/apogee"
  version "0.1.4"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/BIwashi/apogee/releases/download/v0.1.4/apogee_0.1.4_darwin_amd64.tar.gz"
    sha256 "57da111f0726cf103018d6f045d15c064fe2098d81cd997883386893470fb3a5"

    define_method(:install) do
      bin.install "apogee"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/BIwashi/apogee/releases/download/v0.1.4/apogee_0.1.4_darwin_arm64.tar.gz"
    sha256 "eb14403c355f89f327c4ad0222fd59c597bb9da8df2655528170b4436fdabdce"

    define_method(:install) do
      bin.install "apogee"
    end
  end

  test do
    assert_match "apogee v", shell_output("#{bin}/apogee version")
  end
end
